export enum CounterActionType {
  COUNTER_INCREMENT = 'COUNTER_INCREMENT',
  COUNTER_DECREMENT = 'COUNTER_DECREMENT',
}

export enum BooksActionType {
  SET_BOOKS = 'SET_BOOKS',
  SET_BOOKS_LOADING = 'SET_BOOKS_LOADING',
  SET_BOOKS_ERROR = 'SET_BOOKS_ERROR',
}
